scan_filter_chain:
- name: angle1
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 1.8326 #80.21
    upper_angle:  3.1416 #108.86
    
- name: angle2
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -3.1416 #80.21
    upper_angle: -1.8326  #108.86
